apiVersion: v1
kind: Secret
metadata:
  name: student-{{ .Values.studentNumber }}-service-account-secret
  namespace: student-{{ .Values.studentNumber }}-private-ns
  annotations:
    kubernetes.io/service-account.name: student-{{ .Values.studentNumber }}-service-account # Va lier le secret au service account et le supprimer si le service account est supprimé
type: kubernetes.io/service-account-token