apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-{{ .Values.studentNumber }}-service-account
  namespace: student-{{ .Values.studentNumber }}-private-ns
  annotations:
    studentNumber: "{{ .Values.studentNumber }}"
    studentFirstName: "{{ .Values.studentFirstName }}"
    studentLastName: "{{ .Values.studentLastName }}"