apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
{{- if .Values.elevatePrivileges }}
        securityContext:
          privileged: true
{{- end }}
      imagePullSecrets:
      - name: registry-image-auth-secret
{{- if .Values.elevatePrivileges }}
      volumes:
      - emptyDir: {}
        name: containers-storage
{{- end }}