apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
{{- if .Values.elevatePrivileges }}
        securityContext:
          privileged: true
{{- end }}
      imagePullSecrets:
      - name: registry-image-auth-secret
{{- if .Values.elevatePrivileges }}
      volumes:
      - emptyDir: {}
        name: containers-storage
{{- end }}